const actionTypes = {
    GET_ALBUMS : 'GET_ALBUMS',
    GOT_ALBUMS : 'GOT_ALBUMS',

    ADD_ALBUM : 'ADD_ALBUM',
    ADDED_ALBUM : 'ADDED_ALBUM',

    DELETE_ALBUM : 'DELETE_ALBUM',
    DELETED_ALBUM : 'DELTED_ALBUM',

    UPDATE_ALBUM : 'UPDATE_ALBUM',
    UPDATED_ALBUM : 'UPDATED_ALBUM'
}

export default actionTypes